version = 0.1

[default.global.parameters]
stack_name = "eliasb-token-api"

[default.deploy]
[default.deploy.parameters]
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
s3_prefix = "token-api"
region = "eu-west-1"
