AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Service A

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "ServiceA"
      MemorySize: 128
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: "eliasb/dynamodb_table_name"
      Environment:
        Variables:
          DYNAMO_TABLE_SSM: "/eliasb/dynamodb_table_name"
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
