AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Service A

Globals:
  Function:
    Timeout: 5

Parameters:
  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Hosted Zone ID
    Default: /eliasb/hosted_zone_id
  TableName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of the DynamoDB table
    Default: /eliasb/dynamodb_table_name

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "ServiceA"
      MemorySize: 128
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: svca.aws.eliasbrange.dev
      DomainValidationOptions:
        - DomainName: svca.aws.eliasbrange.dev
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      DisableExecuteApiEndpoint: true
      Domain:
        CertificateArn: !Ref Certificate
        DomainName: svca.aws.eliasbrange.dev
        Route53:
          HostedZoneId: !Ref HostedZoneId
