name: "AUTH - Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

permissions:
  id-token: write

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      work_dir: auth
      project_name: Auth
    secrets:
      role: ${{ secrets.AUTH_DEPLOY_ROLE }}
