name: "AUTH - Pull request"

on:
  pull_request:
    branches:
      - main
    paths:
      - "auth/**"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      work_dir: auth
      project_name: Auth
    secrets:
      role: ${{ secrets.AUTH_PR_ROLE }}
