name: "AUTH - Pull request"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      work_dir: auth
      project_name: Auth
