name: "DATABASES - Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "databases/**"

permissions:
  id-token: write

jobs:
  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      work_dir: databases
    secrets:
      role: ${{ secrets.DB_DEPLOY_ROLE }}
