name: "DATABASES - Pull request"

on:
  pull_request:
    branches:
      - main
    paths:
      - "databases/**"

permissions:
  id-token: write
  pull-requests: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      work_dir: databases
      project_name: Databases
    secrets:
      role: ${{ secrets.DB_PR_ROLE }}
