name: "DNS - Pull request"

on:
  pull_request:
    branches:
      - main
    paths:
      - "dns/**"

permissions:
  id-token: write
  pull-requests: write

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      work_dir: dns
      project_name: DNS
    secrets:
      role: ${{ secrets.DNS_PR_ROLE }}
