name: "DOGS API - Deploy"

on:
  push:
    branches:
      - main
    # paths:
      # - "dogs-api/**"

permissions:
  id-token: write

jobs:
  sam-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy with SAM
        uses: ./.github/actions/sam-deploy
        with:
          work_dir: dogs-api
          role: ${{ secrets.SAM_DEPLOY_ROLE }}
